### ISSUE TITLE
Demo中好像没有用到加密，也没有提供注册登录要怎么走？

### ISSUE THREAD

**Issue by SamHz** [Smith-Cruise/Spring-Boot-Security-JWT-SPA#2]
加密和注册登录的加解密或密码比对，这些都是自己来实现吗？

**Comment by Smith-Cruise** [comment]
我 Spring Security 里面 https://github.com/Smith-Cruise/Spring-Boot-Security-JWT-SPA/blob/master/src/main/java/org/inlighting/security/security/SecurityConfiguration.java#L71-L73

这里就是提供了加密解密的算法，框架会自动处理加密解密流程。

**Comment by SamHz** [comment]
SpringSecurity新手，看到这个终于明白了点 https://www.cnblogs.com/loveer/p/11424821.html
