### ISSUE TITLE
CacheManager无法注入

### ISSUE THREAD

**Issue by lgbwust** [Smith-Cruise/Spring-Boot-Security-JWT-SPA#4]
您好，我按照你您的例子，整合了一个demo，但是启动时报错，无法创建CacheManager这个bean，
Consider revisiting the entries above or defining a bean of type 'org.springframework.cache.CacheManager' in your configuration.
我想问一下这是什么原因造成的呢，谢谢！

**Comment by Smith-Cruise** [comment]
你添加了 `@EnableCache` 注解吗

**Comment by lgbwust** [comment]
启动类上面添加了@EnableCaching 还是不行

**Comment by Smith-Cruise** [comment]
`pom.xml` 之类关于注解的依赖没有少吧，你在我的代码里面 ctrl + f 看看关于注解的配置项，你有没有少的。

**Comment by lgbwust** [comment]
谢谢，我已经解决了无法注入的问题。我在application.properties里面加了一个配置
spring.cache.jcache.provider=org.ehcache.jsr107.EhcacheCachingProvider

**Comment by Smith-Cruise** [comment]
可以的😀
