### ISSUE TITLE
关于string与GrantedAuthority collection之间的转换

### ISSUE THREAD

**Issue by pikanglong** [Smith-Cruise/Spring-Boot-Security-JWT-SPA#6]
您在创建UserEntity.java时提到

> 关于 role 为什么使用 GrantedAuthority 说明下：其实是为了简化代码，直接用了 Security 现成的 role 类，实际项目中我们肯定要自己进行处理，将其转换为 Security 的 role 类。

请问这个转换有推荐的教程吗？

我在MySQL数据库中创建类型为varchar(255)的role字段，UserEntity只能通过String读取，但是在UserDetailsServiceImpl.java中传参的时候却需要传Collection<? extends GrantedAuthority>类型的参数。

**Comment by pikanglong** [comment]
已解决。

参考了[这篇文章](https://www.programcreek.com/java-api-examples/org.springframework.security.core.GrantedAuthority)。

将UserDetailsServiceImpl.java的最后改成

```
        List<GrantedAuthority> grantedAuths = AuthorityUtils.commaSeparatedStringToAuthorityList(user.getRole());
        return new org.springframework.security.core.userdetails.User(user.getUsername(), user.getPassword(), grantedAuths);
```

即可。

**Comment by Smith-Cruise** [comment]
其实这个代码我项目里面写了，兄弟不仔细啊。
https://github.com/Smith-Cruise/Spring-Boot-Security-JWT-SPA/blob/master/src/main/java/org/inlighting/security/service/Database.java#L39-L41
