### ISSUE TITLE
jwt生成token的问题

### ISSUE THREAD

**Issue by bigzhouyongqiang** [Smith-Cruise/Spring-Boot-Security-JWT-SPA#7]
您好，我在阅读jwt生成token代码的地方，我看注释写的是生成签名值，但是生成token算法用的是HMAC256，这个算法不是摘要算法吗？是我的理解不正确吗？麻烦解答一下 ，谢谢。

**Comment by Smith-Cruise** [comment]
这个你可以参考JWT官方算法的规范 https://jwt.io/introduction/。

**Comment by bigzhouyongqiang** [comment]
好的，谢谢
